version: "3"
services:
  ## VAULT cluster configuration
  pki: &pki
    image: vault-prem:1.3.4
    volumes:
      - ./pki/ca:/vault/ca
      - ./pki/config:/vault/config
      - ./pki/logs/:/vault/logs
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
      - VAULT_LOG_LEVEL=debug
    command: vault server -config=/vault/config/vault-pki.hcl
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul_agent_1
