version: "3"

services:
  vault01: &vault_server
    image: vault-prem:1.3.4
    environment:
      #- VAULT_CLUSTER_INTERFACE=eth0
      - VAULT_REDIRECT_INTERFACE=eth0
      #- VAULT_API_ADDR=http://vault01:8200
      - VAULT_LOG_LEVEL=debug
    command: vault server -config=/vault/config/vault01.hcl
    cap_add:
      - IPC_LOCK
  vault02:
    <<: *vault_server
    command: vault server -config=/vault/config/vault02.hcl
  vault03:
    <<: *vault_server
    command: vault server -config=/vault/config/vault03.hcl
