#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)
case "$1" in
    "proxy")
    docker-compose --project-directory infra/docker/raft/proxy --project-name raft -f infra/docker/raft/proxy/docker-compose.yml up -d
;;
    "init")
    networks=(
        vault_primary
        vault_secondary
        vault_dr
        vault_primaryA
        vault_primaryB
        vault_primaryC
        vault_secondaryA
        vault_secondaryB
        vault_secondaryC
        vault_drA
        vault_drB
        vault_drC
    )
    for n in ${networks[@]}
    do
        docker network create -d bridge $n
    done
;;
     *)
        echo "${bold}Usage: $0 <command> <subcommand>${normal}"
        echo "Commands:"
        echo "  ${bold}init${normal}: Will initialize the networks"
        echo "  ${bold}proxy${normal}"
        echo "      ${bold}start${normal}:<raft|consul>"
        echo "      ${bold}stop${normal}: <raft|consul>"
;;  
esac