#!/bin/bash -e
####
# INFRA
###
# To enable debug: export DEBUG=true
# Enable debug if the env variable DEBUG is set to true
if [[ "$DEBUG" == "true" ]];then
    set -x
fi
#External variables
if [ "$0" == "infra/docker/p" ]; then
    export VAULT_CLUSTER="primary"
else
    export VAULT_CLUSTER="secondary"
fi
#Internal variables
STORAGE=${STORAGE:-"raft"}
VAULT_VERSION="1.3.4"
COMPOSE_CMD="docker-compose --project-directory infra/docker/${STORAGE} --project-name ${VAULT_CLUSTER}  -f infra/docker/${STORAGE}/vault-${VAULT_CLUSTER}.yml -f infra/docker/${STORAGE}/vault.yml"
bold=$(tput bold)
normal=$(tput sgr0)
typeset -a VAULT_primary_PORTS=("9201" "9202" "9203")
typeset -a VAULT_secondary_PORTS=("9301" "9302" "9303")
typeset -a VAULT_dr_PORTS=("9401" "9402" "9403")

echo "# Using storage: ${STORAGE}"
case "$1" in
    "wipe")
        if [ ! -z "$2" ]; then
             sudo rm -fr infra/docker/storage/raft/${VAULT_CLUSTER}/$2
             mkdir -p infra/docker/storage/raft/${VAULT_CLUSTER}/$2
        else
             sudo rm -fr infra/docker/storage/raft/${VAULT_CLUSTER}
            mkdir -p infra/docker/storage/raft/${VAULT_CLUSTER}/{01,02,03,unsealer,pki}
        fi
    ;;
    "wipe_nodes")
        sudo rm -fr infra/docker/storage/raft/${VAULT_CLUSTER}/{01,02,03}
        mkdir -p infra/docker/storage/raft/${VAULT_CLUSTER}/{01,02,03}
    ;;
    "restart")
        if [ ! -z "$2" ]; then
            ${COMPOSE_CMD} restart $2
        else
            ${COMPOSE_CMD} restart vault01 vault02 vault03
        fi
    ;;
    "stop")
        ${COMPOSE_CMD} stop $2
    ;;
    "down")
         ${COMPOSE_CMD} down
    ;;
    "config")
        ${COMPOSE_CMD} config
    ;;
    "unpause")
        ${COMPOSE_CMD} unpause
    ;;    
    "pause")
        ${COMPOSE_CMD} pause
    ;;    
    "compose")
        ${COMPOSE_CMD} ${@:2}
    ;;
    "up")
        if [ "$3" == "recreate" ]; then
            RECREATE="--force-recreate"
        fi
        echo "Starting up ${VAULT_CLUSTER} Cluster with version $VAULT_VERSION"
        ${COMPOSE_CMD} up -d ${RECREATE} $2 
    ;;
     *)
        echo "${bold}Usage: $0 <command> <subcommand>${normal}"
        echo ""
        echo "${bold}config${normal}: Will execute docker-compose config with the proper templates "
        echo "${bold}up${normal}: This will start the ${VAULT_CLUSTER} Vault cluster"
        echo "${bold}down${normal}: It will do a docker-compose down with the correct template"
        echo "${bold}restart${normal}: Restart the service"

    ;;    
esac