version: "3"
networks:
  vault_secondaryA:
    external: true
  vault_secondaryB:
    external: true
  vault_secondaryC:
    external: true
## VAULT cluster configuration
services:
  vault01:
    ports:
      - 9501:8200
      - 9601:8201
  vault02:
    ports:
      - 9502:8200
      - 9602:8201
  vault03:
    ports:
      - 9503:8200
      - 9603:8201
  vault_unsealer:
    ports:
      - 9500:8200
      - 9600:8201
