version: "3"
services:
  vault01: &vault_server
    container_name: ${VAULT_CLUSTER}-vault01
    image: vault-prem:1.4.0
    environment:
      - VAULT_REDIRECT_INTERFACE=eth0
      - VAULT_TOKEN=autounseal
      #- VAULT_CACERT=/vault/config/ssl/ca.pem
    command: vault server -config=/vault/config/vault01.hcl
    #command: vault server -config=/vault/config/vault01.hcl
    volumes:
      - ./${VAULT_CLUSTER}:/vault/config
      - ./../storage/raft/${VAULT_CLUSTER}/01:/vault/raft
    cap_add:
      - IPC_LOCK
    networks:
      - vault_${VAULT_CLUSTER}A
      - vault_${VAULT_CLUSTER}B
      - vault_${VAULT_CLUSTER}C
  vault02:
    <<: *vault_server
    container_name: ${VAULT_CLUSTER}-vault02
    depends_on:
      - vault_unsealer
    command: vault server -config=/vault/config/vault02.hcl
    volumes:
      - ./${VAULT_CLUSTER}:/vault/config
      - ./../storage/raft/${VAULT_CLUSTER}/02:/vault/raft
  vault03:
    <<: *vault_server
    container_name: ${VAULT_CLUSTER}-vault03
    depends_on:
      - vault_unsealer
    command: vault server -config=/vault/config/vault03.hcl
    volumes:
      - ./${VAULT_CLUSTER}:/vault/config
      - ./../storage/raft/${VAULT_CLUSTER}/03:/vault/raft
  ## Unsealer
  vault_unsealer:
    <<: *vault_server
    container_name: ${VAULT_CLUSTER}-unsealer
    command: vault server -config=/vault/config/vault_unsealer.hcl
    volumes:
      - ./${VAULT_CLUSTER}:/vault/config
      - ./../storage/raft/${VAULT_CLUSTER}/unsealer:/vault/raft
  ## PKI
  vault_pki: &vault_pki
    image: vault-prem:1.4.0
    container_name: ${VAULT_CLUSTER}-pki
    environment:
      - VAULT_TOKEN=autounseal
      - VAULT_LOG_LEVEL=debug
    command: vault server -config=/vault/config/vault_pki.hcl
    volumes:
      - ./${VAULT_CLUSTER}:/vault/config
      - ./../storage/raft/${VAULT_CLUSTER}/pki:/vault/raft
    cap_add:
      - IPC_LOCK
    networks:
      - vault_${VAULT_CLUSTER}A
      - vault_${VAULT_CLUSTER}B
      - vault_${VAULT_CLUSTER}C
