version: "3"
networks:
  vault_primaryA:
    external: true
  vault_primaryB:
    external: true
  vault_primaryC:
    external: true
## VAULT cluster configuration
services:
  vault01:
    ports:
      - 9301:8200
      - 9401:8201
  vault02:
    ports:
      - 9302:8200
      - 9402:8201
  vault03:
    ports:
      - 9303:8200
      - 9403:8201
  vault_unsealer:
    ports:
      - 9300:8200
  vault_pki:
    ports:
      - 9304:8200
