---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: openshift-config
---
apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-config
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: openshift-config
