global:
  enabled: true

injector:
  enabled: true
  image:
    tag: "0.4.0"
  agentImage:
    repository: hashicorp/vault-enterprise
    tag: "1.4.2_ent"

  logLevel: "debug"
  authPath: "auth/kubernetes"

server:
  extraEnvironmentVars:
    VAULT_LOG_LEVEL: "debug"
    GOOGLE_STORAGE_BUCKET: "rodrigo-vault-storage"
    GOOGLE_STORAGE_HA_ENABLED: "true"
  image:
    repository: hashicorp/vault-enterprise
    tag: "1.4.2_ent"

  auditStorage:
    enabled: true
  dataStorage:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    config: |
      disable_mlock = true
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      service_registration "kubernetes" {}
      storage "gcs" {
      }
